[package]
name = "project-smokey"
version = "1.1.0"
edition = "2021"

[dependencies]
tensorflow = { version = "0.19.0", features = ["tensorflow_gpu"] }
rusqlite = { version = "0.28.0", features = ["bundled"] }
